### PR TITLE
Upgrade to 2.7.1 fullcalendar and code cleanup/improvements

### PR DESCRIPTION
**Pull request by peterver**
I made the following improvements : 
- updated FullCalendar to 2.7.1
- tested with angular 1.4.x
- bumped Travis Node version to 5.6
- Added .editorconfig file
- Added .jscscrc file for code styling
- Refactored calendar.js to pass code styling check
- Added a grunt task for jscs
- Adjusted most of the controller functions to make use of native reduce/filter/forEach functions

### CODE REVIEW

**Comment by martin-langhoff** [comment]
Thank you! will be reviewing shortly for merge.

**Comment by peterver** [comment]
We're using this directive in our enterprise package, and i saw that this repo was becoming a bit stale. If you like the adjustments i made i'd be willing to contribute more ( aka i'll do more pull requests in the future if you want me to :] )

**Comment by martin-langhoff** [comment]
Apologies about the delay! This PR looks very good and includes several things I had on my personal TO DO list.

New contributors are welcome, and as you can see, are sorely needed.

Yes to more PRs. Would you like to co-maintain the repo?

**Comment by peterver** [comment]
No worries about the delay :], i'd be happy to co-maintain the repo if needed.

**Pull request merged**
