### PR TITLE
Fix issue with event rendering

### PR DESCRIPTION
**Pull request by maticaputti**
Fix event issue that make them disappear if switch with previous/next or change date from calendar.

### CODE REVIEW

**Comment by flick36** [comment]
#346

**Comment by martin-langhoff** [comment]
My initial reaction to this is so-so. The standard behavior of FC is to default to ephemeral events. angular-ui-calendar is wrapping FC, so overriding FC default behaviors needs to be done with due care.

In my code using angular-ui-calendar, I set sticky in the draggable object "event" properties, or register an `eventReceive()` cb and apply the fixup there.

In other words, sticky definitely deserves an FAQ, but I'm not sure it deserves an override.

@arshaw - I am interested in your take on why FC defaults to ephemeral (sticky: false) for 'received' events from a drag&drop action.

**Comment by arshaw** [comment]
because usually upon drop of an event, a write call is made to the backend DB, and if the user navigates away from the current view and back again, the end-user will receive the newly created event from the DB, and if it was sticky when it was added, they will see two. that was my thought process

**Comment by martin-langhoff** [comment]
@arshaw - thanks!

@maticaputti , @flick36 -- at this time I do not think it is a good idea to merge this. Reasons:

* ui-calendar is a wrapper around FC, and should favor following the FC defaults and behaviors. This default in FC fits one programming pattern as @arshaw points out. Might be surprising for folks using other patterns (as it was for @maticaputti and for me when I used it initially) but that's material for a FAQ.
* This would be a breaking change; affecting users who have been relying on the sticky:false behavior. Breaking changes require major reasons behind them...

I don't like to see a nice convenient patch go to waste but...

**Pull request closed without merging**
