### PR TITLE
Set jshint configuration option 'latedef' to false

### PR DESCRIPTION
**Pull request by crrkit01**
I've set the jshint latedef option to false to get the build to pass.

### CODE REVIEW

**Comment by ballerabdude** [comment]
@crrkit01 what build was failing?

**Comment by crrkit01** [comment]
Before setting 'latedef' to 'false', running grunt would return this jshint error:

    [L7:C22] 'CalendarCtrl' was used before it was defined.
    function CalendarCtrl($scope, $compile, $timeout, uiCalendarConfig) {

This was because jshint was complaining about using a function before it was declared:

    // Lines 4-7 demo/calendarDemo.js
    angular.module('calendarDemoApp', ['ui.calendar', 'ui.bootstrap'])
        .controller('CalendarCtrl', CalendarCtrl);
    
    function CalendarCtrl($scope, $compile, $timeout, uiCalendarConfig) {


Setting 'latedef' to 'true' makes jshint warn about functions being called before they are declared. Since we are not doing that in our code, I've set it to false. I think that's the reason why the travis badge on the readme file is currently red.

**Comment by ballerabdude** [comment]
@crrkit01 update to the latest grunt-contrib-jshint which is version 0.11.2 then instead of making latedef false make it `latedef:'nofunc'`. This will fix that problem but while I was testing I was getting angular is not defined error then I added angular to the global list `globals: { angular: true }`. This was not working. Can you take a look?

**Comment by crrkit01** [comment]
@ballerabdude Thanks for exploring this further.   
    
I just upgraded jshint to 0.11.2 and changed the config to `latedef: 'nofunc'`but it seems to be working fine for me? I am not running into any problems. I will make a push and see if it will work on the travis server.

**Comment by crrkit01** [comment]
@ballerabdude 

Also, should I go ahead and try to update the node version as well as the rest of the other dependencies? Perhaps that's where the difference lies between your run and mine.

**Comment by ballerabdude** [comment]
Thanks @crrkit01 for the fix. This PR https://github.com/angular-ui/ui-calendar/pull/287 already updates the node version so we should just go with it.

**Comment by crrkit01** [comment]
@ballerabdude Awesome! Thanks a lot

**Pull request merged**
