### PR TITLE
Ui cal id removal

### PR DESCRIPTION
**Pull request by joshkurz**
__uiCalId was causing issues with removing and adding events. 
 @glebm was there a specific reason you used __uiCalId?

### CODE REVIEW

**Comment by glebm** [comment]
@joshkurz I used it to indicate that this is a property coming from ui-calendar and not fullcalendar. Remove issue is due to the wrong key being checked in https://github.com/angular-ui/ui-calendar/blob/master/src/calendar.js#L286.

**Comment by glebm** [comment]
[L286](https://github.com/angular-ui/ui-calendar/blob/master/src/calendar.js#L286) should simply be:

```javascript
return e === event;
```

The object passed into the callback is always the original event object.

**Comment by joshkurz** [comment]
@glebm not sure that works. I just tried it out and it the events are different. One is from Angular and one is touched by fc, which does a lot of other things to it, and ads many different items. It seems that _id is our only shot here, as its something that we can persist through, because fc will not overwrite it if we set it. 

I also updated this PR to just send the _id so it is much more performant than before.

**Comment by joshkurz** [comment]
merging this in as its breaking the demo without it. If you see something I did not, please let me know @glebm.

**Pull request merged**
