### PR TITLE
Fix eventFingerPrint when start/end are strings

### PR DESCRIPTION
**Pull request by antoinepairet**
Based on #281

### CODE REVIEW

**Comment by ballerabdude** [comment]
@antoinepairet There were some PR that was merged in yesterday can you pull the latest and send a PR again thanks.

**Comment by antoinepairet** [comment]
@ballerabdude which branch should I fork? I did fork master 4 hours ago to create this PR. Is there something I am missing?

regards

**Comment by ballerabdude** [comment]
I just merged it

**Comment by antoinepairet** [comment]
@ballerabdude thanks!
Looking forward contributing more to the project

regards

**Pull request merged**
